
% ----------------------------------------------
% Epic Explorer simulation file - created on Mon Mar 24 11:48:30 2014

% Objectives: Average Power, Execution Time
% Benchmark: fib
% Compiler: tcc_region, max_unroll_allowed, regroup_only, do_classic_opti, do_prepass_scalar_scheduling, do_postpass_scalar_scheduling, do_modulo_scheduling, memvr_profiled

% Area(cm^2)  Power(W)     Time(ms)   / MHz / cl / I F B M / gpr fpr pr cr btr / L1D(CBA) / L1I(CBA) / L2U(CBA) / Compiler
% ----------------------------------------------
1.264273482  20644043872040.812500000  0.002210000 %/ 200 / 1 / 6 3 4 4 / 128 16 64 128 16 / 16384 64 2 / 4096 64 4 / 524288 128 8 / 2 8 1 1 2 1 1 1  