
% ----------------------------------------------
% Epic Explorer simulation file - created on Wed Oct 22 21:25:53 2014

% Objectives: Average Power, Execution Time
% Benchmark: alloca_test
% Compiler: tcc_region, max_unroll_allowed, regroup_only, do_classic_opti, do_prepass_scalar_scheduling, do_postpass_scalar_scheduling, do_modulo_scheduling, memvr_profiled

% Area(cm^2)  Power(W)     Time(ms)   / MHz / cl / I F B M / gpr fpr pr cr btr / L1D(CBA) / L1I(CBA) / L2U(CBA) / Compiler
% ----------------------------------------------
1.861802440  2.602469006  0.005890000 %/ 200 / 2 / 4 3 4 2 / 32 64 128 64 32 / 32768 64 4 / 8192 128 2 / 65536 256 16 / 1 32 2 1 1 2 2 1  
0.478251423  1.850016359  0.010865000 %/ 200 / 1 / 6 2 1 2 / 32 32 64 64 32 / 32768 128 4 / 32768 64 2 / 65536 128 4 / 2 8 1 2 1 2 1 2  